### ISSUE TITLE
Depreciation warning: please use MorganGenerator

### ISSUE THREAD

**Issue by MightyFu** [swansonk14/admet_ai#10] opened 2024-08-23 03:38 UTC
Hi Kyle, thanks so much for putting this togther. I have encounterd a "Depreciation warning: please use MorganGenerator." as a repeated error message when running the local python version.

I think this RDKit blog covers the problem https://greglandrum.github.io/rdkit-blog/posts/2023-01-18-fingerprint-generator-tutorial.html

All the best

**Comment by davide-grheco** [comment] 2024-08-28 12:28
This is a problem with Chemprop, I do not think it can be fixed unless they retrain all the models.
It should not be a problem unless RDKit actually removes the function, until then you can just disable the RDKit error message.

**Comment by swansonk14** [comment] 2024-09-02 18:34
@MightyFu, thank you for raising the issue! Unfortunately, as @davide-grheco noted, the deprecation warning is related to RDKit fingerprint generation which is not directly computed by the ADMET-AI package. It instead comes from the [descriptastorus](https://github.com/bp-kelley/descriptastorus) package, which is used by ADMET-AI via [chemfunc](https://github.com/swansonk14/chemfunc) and [chemprop](https://github.com/chemprop/chemprop) to compute those RDKit fingerprints. I raised an [issue](https://github.com/bp-kelley/descriptastorus/issues/32) on the descriptastorus GitHub page, so hopefully once the problem is resolved there, we can update descriptastorus to remove those deprecation warnings.

**Comment by swansonk14** [comment] 2024-09-08 23:01
As a quick update on this discussion, there is a planned update to the descriptastorus package promised in the next couple of weeks (see [here](https://github.com/bp-kelley/descriptastorus/issues/32)). Once the update is pushed, I'll update the descriptastorus version requirement for ADMET-AI.

**Comment by swansonk14** [comment] 2024-10-11 19:09
This issue has now been fixed on descriptastorus with the newest version, 2.7.0.5. If you run `pip install --upgrade chemfunc` and `pip install --upgrade descriptastorus` and then retry your commands, that should remove the deprecation warnings. Please let me know if you're still running into any issues!

**Closed by swansonk14** 2024-10-11 19:09 UTC
